language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t mjdavy/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mjdavy/docker-react npm run test